@host = http://localhost:5045
@dinnerHostId = 4467e124-55bc-417d-ab3d-08c1d442dd68
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGYzMDIzYy04NDM0LTRlYjAtOGQ2ZS03Y2NmOTNkZDAyNWMiLCJnaXZlbl9uYW1lIjoiQWxleCIsImZhbWlseV9uYW1lIjoiS296aHNhc2giLCJqdGkiOiIyYTZkNmY5NC1kOTlhLTQyNjQtYTBkMy01NzMyZWM0YThlMzEiLCJleHAiOjE3MTc1OTgyMzcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.x0G8jJaf_oa_QDnbMuQq_C3WlqtV940wdP1pHz8X6vY

POST {{host}}/hosts/{{dinnerHostId}}/menus HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu Name 2",
  "description": "Menu Description 2",
  "sections": [
    {
      "name": "Section name",
      "description": "Section description",
      "items": [
        {
          "name": "Item name",
          "description": "Item description"
        }
      ]
    }
  ]
}
